heroData = {'ABADDON': ['Melee', 'Support', 'Carry', 'Durable'],
             'ALCHEMIST': ['Melee',
                           'Carry',
                           'Support',
                           'Durable',
                           'Disabler',
                           'Initiator',
                           'Nuker'],
             'ANCIENT APPARITION': ['Ranged', 'Support', 'Disabler', 'Nuker'],
             'ANTI-MAGE': ['Melee', 'Carry', 'Escape', 'Nuker'],
             'ARC WARDEN': ['Ranged', 'Carry', 'Escape', 'Nuker'],
             'AXE': ['Melee', 'Initiator', 'Durable', 'Disabler', 'Jungler'],
             'BANE': ['Ranged', 'Support', 'Disabler', 'Nuker', 'Durable'],
             'BATRIDER': ['Ranged',
                          'Initiator',
                          'Jungler',
                          'Disabler',
                          'Escape'],
             'BEASTMASTER': ['Melee',
                             'Initiator',
                             'Disabler',
                             'Durable',
                             'Nuker'],
             'BLOODSEEKER': ['Melee',
                             'Carry',
                             'Disabler',
                             'Jungler',
                             'Nuker',
                             'Initiator'],
             'BOUNTY HUNTER': ['Melee', 'Escape', 'Nuker'],
             'BREWMASTER': ['Melee',
                            'Carry',
                            'Initiator',
                            'Durable',
                            'Disabler',
                            'Nuker'],
             'BRISTLEBACK': ['Melee', 'Carry', 'Durable', 'Initiator', 'Nuker'],
             'BROODMOTHER': ['Melee', 'Carry', 'Pusher', 'Escape', 'Nuker'],
             'CENTAUR WARRUNNER': ['Melee',
                                   'Durable',
                                   'Initiator',
                                   'Disabler',
                                   'Nuker',
                                   'Escape'],
             'CHAOS KNIGHT': ['Melee',
                              'Carry',
                              'Disabler',
                              'Durable',
                              'Pusher',
                              'Initiator'],
             'CHEN': ['Ranged', 'Support', 'Jungler', 'Pusher'],
             'CLINKZ': ['Ranged', 'Carry', 'Escape', 'Pusher'],
             'CLOCKWERK': ['Melee',
                           'Initiator',
                           'Disabler',
                           'Durable',
                           'Nuker'],
             'CRYSTAL MAIDEN': ['Ranged',
                                'Support',
                                'Disabler',
                                'Nuker',
                                'Jungler'],
             'DARK SEER': ['Melee',
                           'Initiator',
                           'Jungler',
                           'Escape',
                           'Disabler'],
             'DARK WILLOW': ['Ranged',
                             'Support',
                             'Nuker',
                             'Disabler',
                             'Escape'],
             'DAZZLE': ['Ranged', 'Support', 'Nuker', 'Disabler'],
             'DEATH PROPHET': ['Ranged',
                               'Carry',
                               'Pusher',
                               'Nuker',
                               'Disabler'],
             'DISRUPTOR': ['Ranged',
                           'Support',
                           'Disabler',
                           'Nuker',
                           'Initiator'],
             'DOOM': ['Melee',
                      'Carry',
                      'Disabler',
                      'Initiator',
                      'Durable',
                      'Nuker'],
             'DRAGON KNIGHT': ['Melee',
                               'Carry',
                               'Pusher',
                               'Durable',
                               'Disabler',
                               'Initiator',
                               'Nuker'],
             'DROW RANGER': ['Ranged', 'Carry', 'Disabler', 'Pusher'],
             'EARTH SPIRIT': ['Melee',
                              'Nuker',
                              'Escape',
                              'Disabler',
                              'Initiator',
                              'Durable'],
             'EARTHSHAKER': ['Melee',
                             'Support',
                             'Initiator',
                             'Disabler',
                             'Nuker'],
             'ELDER TITAN': ['Melee',
                             'Initiator',
                             'Disabler',
                             'Nuker',
                             'Durable'],
             'EMBER SPIRIT': ['Melee',
                              'Carry',
                              'Escape',
                              'Nuker',
                              'Disabler',
                              'Initiator'],
             'ENCHANTRESS': ['Ranged',
                             'Support',
                             'Jungler',
                             'Pusher',
                             'Durable',
                             'Disabler'],
             'ENIGMA': ['Ranged', 'Disabler', 'Jungler', 'Initiator', 'Pusher'],
             'FACELESS VOID': ['Melee',
                               'Carry',
                               'Initiator',
                               'Disabler',
                               'Escape',
                               'Durable'],
             'GRIMSTROKE': ['Ranged', 'Support', 'Nuker', 'Disabler', 'Escape'],
             'GYROCOPTER': ['Ranged', 'Carry', 'Nuker', 'Disabler'],
             'HUSKAR': ['Ranged', 'Carry', 'Durable', 'Initiator'],
             'INVOKER': ['Ranged',
                         'Carry',
                         'Nuker',
                         'Disabler',
                         'Escape',
                         'Pusher'],
             'IO': ['Ranged', 'Support', 'Escape', 'Nuker'],
             'JAKIRO': ['Ranged', 'Support', 'Nuker', 'Pusher', 'Disabler'],
             'JUGGERNAUT': ['Melee', 'Carry', 'Pusher', 'Escape'],
             'KEEPER OF THE LIGHT': ['Ranged',
                                     'Support',
                                     'Nuker',
                                     'Disabler',
                                     'Jungler'],
             'KUNKKA': ['Melee',
                        'Carry',
                        'Support',
                        'Disabler',
                        'Initiator',
                        'Durable',
                        'Nuker'],
             'LEGION COMMANDER': ['Melee',
                                  'Carry',
                                  'Disabler',
                                  'Initiator',
                                  'Durable',
                                  'Nuker'],
             'LESHRAC': ['Ranged',
                         'Carry',
                         'Support',
                         'Nuker',
                         'Pusher',
                         'Disabler'],
             'LICH': ['Ranged', 'Support', 'Nuker'],
             'LIFESTEALER': ['Melee',
                             'Carry',
                             'Durable',
                             'Jungler',
                             'Escape',
                             'Disabler'],
             'LINA': ['Ranged', 'Support', 'Carry', 'Nuker', 'Disabler'],
             'LION': ['Ranged', 'Support', 'Disabler', 'Nuker', 'Initiator'],
             'LONE DRUID': ['Ranged', 'Carry', 'Pusher', 'Jungler', 'Durable'],
             'LUNA': ['Ranged', 'Carry', 'Nuker', 'Pusher'],
             'LYCAN': ['Melee',
                       'Carry',
                       'Pusher',
                       'Jungler',
                       'Durable',
                       'Escape'],
             'MAGNUS': ['Melee', 'Initiator', 'Disabler', 'Nuker', 'Escape'],
             'MARS': ['Melee', 'Carry', 'Initiator', 'Disabler', 'Durable'],
             'MEDUSA': ['Ranged', 'Carry', 'Disabler', 'Durable'],
             'MEEPO': ['Melee',
                       'Carry',
                       'Escape',
                       'Nuker',
                       'Disabler',
                       'Initiator',
                       'Pusher'],
             'MIRANA': ['Ranged',
                        'Carry',
                        'Support',
                        'Escape',
                        'Nuker',
                        'Disabler'],
             'MONKEY KING': ['Melee',
                             'Carry',
                             'Escape',
                             'Disabler',
                             'Initiator'],
             'MORPHLING': ['Ranged',
                           'Carry',
                           'Escape',
                           'Durable',
                           'Nuker',
                           'Disabler'],
             'NAGA SIREN': ['Melee',
                            'Carry',
                            'Support',
                            'Pusher',
                            'Disabler',
                            'Initiator',
                            'Escape'],
             "NATURE'S PROPHET": ['Ranged',
                                  'Carry',
                                  'Jungler',
                                  'Pusher',
                                  'Escape',
                                  'Nuker'],
             'NECROPHOS': ['Ranged', 'Carry', 'Nuker', 'Durable', 'Disabler'],
             'NIGHT STALKER': ['Melee',
                               'Carry',
                               'Initiator',
                               'Durable',
                               'Disabler',
                               'Nuker'],
             'NYX ASSASSIN': ['Melee',
                              'Disabler',
                              'Nuker',
                              'Initiator',
                              'Escape'],
             'OGRE MAGI': ['Melee',
                           'Support',
                           'Nuker',
                           'Disabler',
                           'Durable',
                           'Initiator'],
             'OMNIKNIGHT': ['Melee', 'Support', 'Durable', 'Nuker'],
             'ORACLE': ['Ranged', 'Support', 'Nuker', 'Disabler', 'Escape'],
             'OUTWORLD DEVOURER': ['Ranged', 'Carry', 'Nuker', 'Disabler'],
             'PANGOLIER': ['Melee',
                           'Carry',
                           'Nuker',
                           'Disabler',
                           'Durable',
                           'Escape',
                           'Initiator'],
             'PHANTOM ASSASSIN': ['Melee', 'Carry', 'Escape'],
             'PHANTOM LANCER': ['Melee', 'Carry', 'Escape', 'Pusher', 'Nuker'],
             'PHOENIX': ['Ranged',
                         'Support',
                         'Nuker',
                         'Initiator',
                         'Escape',
                         'Disabler'],
             'PUCK': ['Ranged', 'Initiator', 'Disabler', 'Escape', 'Nuker'],
             'PUDGE': ['Melee', 'Disabler', 'Initiator', 'Durable', 'Nuker'],
             'PUGNA': ['Ranged', 'Nuker', 'Pusher'],
             'QUEEN OF PAIN': ['Ranged', 'Carry', 'Nuker', 'Escape'],
             'RAZOR': ['Ranged', 'Carry', 'Durable', 'Nuker', 'Pusher'],
             'RIKI': ['Melee', 'Carry', 'Escape', 'Disabler'],
             'RUBICK': ['Ranged', 'Support', 'Disabler', 'Nuker'],
             'SAND KING': ['Melee',
                           'Initiator',
                           'Disabler',
                           'Support',
                           'Nuker',
                           'Escape',
                           'Jungler'],
             'SHADOW DEMON': ['Ranged',
                              'Support',
                              'Disabler',
                              'Initiator',
                              'Nuker'],
             'SHADOW FIEND': ['Ranged', 'Carry', 'Nuker'],
             'SHADOW SHAMAN': ['Ranged',
                               'Support',
                               'Pusher',
                               'Disabler',
                               'Nuker',
                               'Initiator'],
             'SILENCER': ['Ranged',
                          'Carry',
                          'Support',
                          'Disabler',
                          'Initiator',
                          'Nuker'],
             'SKYWRATH MAGE': ['Ranged', 'Support', 'Nuker', 'Disabler'],
             'SLARDAR': ['Melee',
                         'Carry',
                         'Durable',
                         'Initiator',
                         'Disabler',
                         'Escape'],
             'SLARK': ['Melee', 'Carry', 'Escape', 'Disabler', 'Nuker'],
             'SNAPFIRE': ['Ranged', 'Support', 'Nuker', 'Disabler', 'Escape'],
             'SNIPER': ['Ranged', 'Carry', 'Nuker'],
             'SPECTRE': ['Melee', 'Carry', 'Durable', 'Escape'],
             'SPIRIT BREAKER': ['Melee',
                                'Carry',
                                'Initiator',
                                'Disabler',
                                'Durable',
                                'Escape'],
             'STORM SPIRIT': ['Ranged',
                              'Carry',
                              'Escape',
                              'Nuker',
                              'Initiator',
                              'Disabler'],
             'SVEN': ['Melee',
                      'Carry',
                      'Disabler',
                      'Initiator',
                      'Durable',
                      'Nuker'],
             'TECHIES': ['Ranged', 'Nuker', 'Disabler'],
             'TEMPLAR ASSASSIN': ['Ranged', 'Carry', 'Escape'],
             'TERRORBLADE': ['Melee', 'Carry', 'Pusher', 'Nuker'],
             'TIDEHUNTER': ['Melee',
                            'Initiator',
                            'Durable',
                            'Disabler',
                            'Nuker'],
             'TIMBERSAW': ['Melee', 'Nuker', 'Durable', 'Escape'],
             'TINKER': ['Ranged', 'Carry', 'Nuker', 'Pusher'],
             'TINY': ['Melee',
                      'Carry',
                      'Nuker',
                      'Pusher',
                      'Initiator',
                      'Durable',
                      'Disabler'],
             'TREANT PROTECTOR': ['Melee',
                                  'Support',
                                  'Initiator',
                                  'Durable',
                                  'Disabler',
                                  'Escape'],
             'TROLL WARLORD': ['Ranged',
                               'Carry',
                               'Pusher',
                               'Disabler',
                               'Durable'],
             'TUSK': ['Melee', 'Initiator', 'Disabler', 'Nuker'],
             'UNDERLORD': ['Melee',
                           'Support',
                           'Nuker',
                           'Disabler',
                           'Durable',
                           'Escape'],
             'UNDYING': ['Melee', 'Support', 'Durable', 'Disabler', 'Nuker'],
             'URSA': ['Melee', 'Carry', 'Jungler', 'Durable', 'Disabler'],
             'VENGEFUL SPIRIT': ['Ranged',
                                 'Support',
                                 'Initiator',
                                 'Disabler',
                                 'Nuker',
                                 'Escape'],
             'VENOMANCER': ['Ranged',
                            'Support',
                            'Nuker',
                            'Initiator',
                            'Pusher',
                            'Disabler'],
             'VIPER': ['Ranged', 'Carry', 'Durable', 'Initiator', 'Disabler'],
             'VISAGE': ['Ranged',
                        'Support',
                        'Nuker',
                        'Durable',
                        'Disabler',
                        'Pusher'],
             'VOID SPIRIT': ['Melee', 'Carry', 'Escape', 'Nuker', 'Disabler'],
             'WARLOCK': ['Ranged', 'Support', 'Initiator', 'Disabler'],
             'WEAVER': ['Ranged', 'Carry', 'Escape'],
             'WINDRANGER': ['Ranged',
                            'Carry',
                            'Support',
                            'Disabler',
                            'Escape',
                            'Nuker'],
             'WINTER WYVERN': ['Ranged', 'Support', 'Disabler', 'Nuker'],
             'WITCH DOCTOR': ['Ranged', 'Support', 'Nuker', 'Disabler'],
             'WRAITH KING': ['Melee',
                             'Carry',
                             'Support',
                             'Durable',
                             'Disabler',
                             'Initiator'],
             'ZEUS': ['Ranged', 'Nuker']}