styleData = {'Carry': ['SVEN',
                       'TINY',
                       'KUNKKA',
                       'DRAGON KNIGHT',
                       'HUSKAR',
                       'ALCHEMIST',
                       'BREWMASTER',
                       'BRISTLEBACK',
                       'LEGION COMMANDER',
                       'MARS',
                       'ANTI-MAGE',
                       'DROW RANGER',
                       'JUGGERNAUT',
                       'MIRANA',
                       'MORPHLING',
                       'PHANTOM LANCER',
                       'RIKI',
                       'SNIPER',
                       'TEMPLAR ASSASSIN',
                       'LUNA',
                       'URSA',
                       'GYROCOPTER',
                       'LONE DRUID',
                       'NAGA SIREN',
                       'TROLL WARLORD',
                       'EMBER SPIRIT',
                       'MONKEY KING',
                       'PANGOLIER',
                       'STORM SPIRIT',
                       'WINDRANGER',
                       'LINA',
                       'TINKER',
                       "NATURE'S PROPHET",
                       'SILENCER',
                       'VOID SPIRIT',
                       'SLARDAR',
                       'WRAITH KING',
                       'LIFESTEALER',
                       'NIGHT STALKER',
                       'DOOM',
                       'SPIRIT BREAKER',
                       'LYCAN',
                       'CHAOS KNIGHT',
                       'ABADDON',
                       'BLOODSEEKER',
                       'SHADOW FIEND',
                       'RAZOR',
                       'FACELESS VOID',
                       'PHANTOM ASSASSIN',
                       'VIPER',
                       'CLINKZ',
                       'BROODMOTHER',
                       'WEAVER',
                       'SPECTRE',
                       'MEEPO',
                       'SLARK',
                       'MEDUSA',
                       'TERRORBLADE',
                       'ARC WARDEN',
                       'NECROPHOS',
                       'QUEEN OF PAIN',
                       'DEATH PROPHET',
                       'LESHRAC',
                       'INVOKER',
                       'OUTWORLD DEVOURER'],
             'Disabler': ['EARTHSHAKER',
                          'SVEN',
                          'TINY',
                          'KUNKKA',
                          'BEASTMASTER',
                          'DRAGON KNIGHT',
                          'CLOCKWERK',
                          'ALCHEMIST',
                          'BREWMASTER',
                          'TREANT PROTECTOR',
                          'CENTAUR WARRUNNER',
                          'TUSK',
                          'ELDER TITAN',
                          'LEGION COMMANDER',
                          'EARTH SPIRIT',
                          'PHOENIX',
                          'MARS',
                          'SNAPFIRE',
                          'DROW RANGER',
                          'MIRANA',
                          'MORPHLING',
                          'VENGEFUL SPIRIT',
                          'RIKI',
                          'URSA',
                          'GYROCOPTER',
                          'NAGA SIREN',
                          'TROLL WARLORD',
                          'EMBER SPIRIT',
                          'MONKEY KING',
                          'PANGOLIER',
                          'CRYSTAL MAIDEN',
                          'PUCK',
                          'STORM SPIRIT',
                          'WINDRANGER',
                          'LINA',
                          'SHADOW SHAMAN',
                          'ENCHANTRESS',
                          'JAKIRO',
                          'SILENCER',
                          'OGRE MAGI',
                          'RUBICK',
                          'DISRUPTOR',
                          'KEEPER OF THE LIGHT',
                          'SKYWRATH MAGE',
                          'ORACLE',
                          'TECHIES',
                          'DARK WILLOW',
                          'VOID SPIRIT',
                          'AXE',
                          'PUDGE',
                          'SAND KING',
                          'SLARDAR',
                          'TIDEHUNTER',
                          'WRAITH KING',
                          'LIFESTEALER',
                          'NIGHT STALKER',
                          'DOOM',
                          'SPIRIT BREAKER',
                          'CHAOS KNIGHT',
                          'UNDYING',
                          'MAGNUS',
                          'UNDERLORD',
                          'BLOODSEEKER',
                          'VENOMANCER',
                          'FACELESS VOID',
                          'VIPER',
                          'MEEPO',
                          'NYX ASSASSIN',
                          'SLARK',
                          'MEDUSA',
                          'BANE',
                          'LION',
                          'WITCH DOCTOR',
                          'ENIGMA',
                          'NECROPHOS',
                          'WARLOCK',
                          'DEATH PROPHET',
                          'DAZZLE',
                          'LESHRAC',
                          'DARK SEER',
                          'BATRIDER',
                          'ANCIENT APPARITION',
                          'INVOKER',
                          'OUTWORLD DEVOURER',
                          'SHADOW DEMON',
                          'VISAGE',
                          'WINTER WYVERN',
                          'GRIMSTROKE'],
             'Durable': ['SVEN',
                         'TINY',
                         'KUNKKA',
                         'BEASTMASTER',
                         'DRAGON KNIGHT',
                         'CLOCKWERK',
                         'OMNIKNIGHT',
                         'HUSKAR',
                         'ALCHEMIST',
                         'BREWMASTER',
                         'TREANT PROTECTOR',
                         'CENTAUR WARRUNNER',
                         'TIMBERSAW',
                         'BRISTLEBACK',
                         'ELDER TITAN',
                         'LEGION COMMANDER',
                         'EARTH SPIRIT',
                         'MARS',
                         'MORPHLING',
                         'URSA',
                         'LONE DRUID',
                         'TROLL WARLORD',
                         'PANGOLIER',
                         'ENCHANTRESS',
                         'OGRE MAGI',
                         'AXE',
                         'PUDGE',
                         'SLARDAR',
                         'TIDEHUNTER',
                         'WRAITH KING',
                         'LIFESTEALER',
                         'NIGHT STALKER',
                         'DOOM',
                         'SPIRIT BREAKER',
                         'LYCAN',
                         'CHAOS KNIGHT',
                         'UNDYING',
                         'ABADDON',
                         'UNDERLORD',
                         'RAZOR',
                         'FACELESS VOID',
                         'VIPER',
                         'SPECTRE',
                         'MEDUSA',
                         'BANE',
                         'NECROPHOS',
                         'VISAGE'],
             'Escape': ['TREANT PROTECTOR',
                        'IO',
                        'CENTAUR WARRUNNER',
                        'TIMBERSAW',
                        'EARTH SPIRIT',
                        'PHOENIX',
                        'SNAPFIRE',
                        'ANTI-MAGE',
                        'JUGGERNAUT',
                        'MIRANA',
                        'MORPHLING',
                        'PHANTOM LANCER',
                        'VENGEFUL SPIRIT',
                        'RIKI',
                        'TEMPLAR ASSASSIN',
                        'BOUNTY HUNTER',
                        'NAGA SIREN',
                        'EMBER SPIRIT',
                        'MONKEY KING',
                        'PANGOLIER',
                        'PUCK',
                        'STORM SPIRIT',
                        'WINDRANGER',
                        "NATURE'S PROPHET",
                        'ORACLE',
                        'DARK WILLOW',
                        'VOID SPIRIT',
                        'SAND KING',
                        'SLARDAR',
                        'LIFESTEALER',
                        'SPIRIT BREAKER',
                        'LYCAN',
                        'MAGNUS',
                        'UNDERLORD',
                        'FACELESS VOID',
                        'PHANTOM ASSASSIN',
                        'CLINKZ',
                        'BROODMOTHER',
                        'WEAVER',
                        'SPECTRE',
                        'MEEPO',
                        'NYX ASSASSIN',
                        'SLARK',
                        'ARC WARDEN',
                        'QUEEN OF PAIN',
                        'DARK SEER',
                        'BATRIDER',
                        'INVOKER',
                        'GRIMSTROKE'],
             'Initiator': ['EARTHSHAKER',
                           'SVEN',
                           'TINY',
                           'KUNKKA',
                           'BEASTMASTER',
                           'DRAGON KNIGHT',
                           'CLOCKWERK',
                           'HUSKAR',
                           'ALCHEMIST',
                           'BREWMASTER',
                           'TREANT PROTECTOR',
                           'CENTAUR WARRUNNER',
                           'BRISTLEBACK',
                           'TUSK',
                           'ELDER TITAN',
                           'LEGION COMMANDER',
                           'EARTH SPIRIT',
                           'PHOENIX',
                           'MARS',
                           'VENGEFUL SPIRIT',
                           'NAGA SIREN',
                           'EMBER SPIRIT',
                           'MONKEY KING',
                           'PANGOLIER',
                           'PUCK',
                           'STORM SPIRIT',
                           'SHADOW SHAMAN',
                           'SILENCER',
                           'OGRE MAGI',
                           'DISRUPTOR',
                           'AXE',
                           'PUDGE',
                           'SAND KING',
                           'SLARDAR',
                           'TIDEHUNTER',
                           'WRAITH KING',
                           'NIGHT STALKER',
                           'DOOM',
                           'SPIRIT BREAKER',
                           'CHAOS KNIGHT',
                           'MAGNUS',
                           'BLOODSEEKER',
                           'VENOMANCER',
                           'FACELESS VOID',
                           'VIPER',
                           'MEEPO',
                           'NYX ASSASSIN',
                           'LION',
                           'ENIGMA',
                           'WARLOCK',
                           'DARK SEER',
                           'BATRIDER',
                           'SHADOW DEMON'],
             'Jungler': ['URSA',
                         'LONE DRUID',
                         'CRYSTAL MAIDEN',
                         "NATURE'S PROPHET",
                         'ENCHANTRESS',
                         'CHEN',
                         'KEEPER OF THE LIGHT',
                         'AXE',
                         'SAND KING',
                         'LIFESTEALER',
                         'LYCAN',
                         'BLOODSEEKER',
                         'ENIGMA',
                         'DARK SEER',
                         'BATRIDER'],
             'Melee': ['EARTHSHAKER',
                       'SVEN',
                       'TINY',
                       'KUNKKA',
                       'BEASTMASTER',
                       'DRAGON KNIGHT',
                       'CLOCKWERK',
                       'OMNIKNIGHT',
                       'ALCHEMIST',
                       'BREWMASTER',
                       'TREANT PROTECTOR',
                       'CENTAUR WARRUNNER',
                       'TIMBERSAW',
                       'BRISTLEBACK',
                       'TUSK',
                       'ELDER TITAN',
                       'LEGION COMMANDER',
                       'EARTH SPIRIT',
                       'MARS',
                       'ANTI-MAGE',
                       'JUGGERNAUT',
                       'PHANTOM LANCER',
                       'RIKI',
                       'BOUNTY HUNTER',
                       'URSA',
                       'NAGA SIREN',
                       'EMBER SPIRIT',
                       'MONKEY KING',
                       'PANGOLIER',
                       'OGRE MAGI',
                       'VOID SPIRIT',
                       'AXE',
                       'PUDGE',
                       'SAND KING',
                       'SLARDAR',
                       'TIDEHUNTER',
                       'WRAITH KING',
                       'LIFESTEALER',
                       'NIGHT STALKER',
                       'DOOM',
                       'SPIRIT BREAKER',
                       'LYCAN',
                       'CHAOS KNIGHT',
                       'UNDYING',
                       'MAGNUS',
                       'ABADDON',
                       'UNDERLORD',
                       'BLOODSEEKER',
                       'FACELESS VOID',
                       'PHANTOM ASSASSIN',
                       'BROODMOTHER',
                       'SPECTRE',
                       'MEEPO',
                       'NYX ASSASSIN',
                       'SLARK',
                       'TERRORBLADE',
                       'DARK SEER'],
             'Nuker': ['EARTHSHAKER',
                       'SVEN',
                       'TINY',
                       'KUNKKA',
                       'BEASTMASTER',
                       'DRAGON KNIGHT',
                       'CLOCKWERK',
                       'OMNIKNIGHT',
                       'ALCHEMIST',
                       'BREWMASTER',
                       'IO',
                       'CENTAUR WARRUNNER',
                       'TIMBERSAW',
                       'BRISTLEBACK',
                       'TUSK',
                       'ELDER TITAN',
                       'LEGION COMMANDER',
                       'EARTH SPIRIT',
                       'PHOENIX',
                       'SNAPFIRE',
                       'ANTI-MAGE',
                       'MIRANA',
                       'MORPHLING',
                       'PHANTOM LANCER',
                       'VENGEFUL SPIRIT',
                       'SNIPER',
                       'LUNA',
                       'BOUNTY HUNTER',
                       'GYROCOPTER',
                       'EMBER SPIRIT',
                       'PANGOLIER',
                       'CRYSTAL MAIDEN',
                       'PUCK',
                       'STORM SPIRIT',
                       'WINDRANGER',
                       'ZEUS',
                       'LINA',
                       'SHADOW SHAMAN',
                       'TINKER',
                       "NATURE'S PROPHET",
                       'JAKIRO',
                       'SILENCER',
                       'OGRE MAGI',
                       'RUBICK',
                       'DISRUPTOR',
                       'KEEPER OF THE LIGHT',
                       'SKYWRATH MAGE',
                       'ORACLE',
                       'TECHIES',
                       'DARK WILLOW',
                       'VOID SPIRIT',
                       'PUDGE',
                       'SAND KING',
                       'TIDEHUNTER',
                       'NIGHT STALKER',
                       'DOOM',
                       'UNDYING',
                       'MAGNUS',
                       'UNDERLORD',
                       'BLOODSEEKER',
                       'SHADOW FIEND',
                       'RAZOR',
                       'VENOMANCER',
                       'BROODMOTHER',
                       'MEEPO',
                       'NYX ASSASSIN',
                       'SLARK',
                       'TERRORBLADE',
                       'ARC WARDEN',
                       'BANE',
                       'LICH',
                       'LION',
                       'WITCH DOCTOR',
                       'NECROPHOS',
                       'QUEEN OF PAIN',
                       'DEATH PROPHET',
                       'PUGNA',
                       'DAZZLE',
                       'LESHRAC',
                       'ANCIENT APPARITION',
                       'INVOKER',
                       'OUTWORLD DEVOURER',
                       'SHADOW DEMON',
                       'VISAGE',
                       'WINTER WYVERN',
                       'GRIMSTROKE'],
             'Pusher': ['TINY',
                        'DRAGON KNIGHT',
                        'DROW RANGER',
                        'JUGGERNAUT',
                        'PHANTOM LANCER',
                        'LUNA',
                        'LONE DRUID',
                        'NAGA SIREN',
                        'TROLL WARLORD',
                        'SHADOW SHAMAN',
                        'TINKER',
                        "NATURE'S PROPHET",
                        'ENCHANTRESS',
                        'JAKIRO',
                        'CHEN',
                        'LYCAN',
                        'CHAOS KNIGHT',
                        'RAZOR',
                        'VENOMANCER',
                        'CLINKZ',
                        'BROODMOTHER',
                        'MEEPO',
                        'TERRORBLADE',
                        'ENIGMA',
                        'DEATH PROPHET',
                        'PUGNA',
                        'LESHRAC',
                        'INVOKER',
                        'VISAGE'],
             'Ranged': ['HUSKAR',
                        'IO',
                        'PHOENIX',
                        'SNAPFIRE',
                        'DROW RANGER',
                        'MIRANA',
                        'MORPHLING',
                        'VENGEFUL SPIRIT',
                        'SNIPER',
                        'TEMPLAR ASSASSIN',
                        'LUNA',
                        'GYROCOPTER',
                        'LONE DRUID',
                        'TROLL WARLORD',
                        'CRYSTAL MAIDEN',
                        'PUCK',
                        'STORM SPIRIT',
                        'WINDRANGER',
                        'ZEUS',
                        'LINA',
                        'SHADOW SHAMAN',
                        'TINKER',
                        "NATURE'S PROPHET",
                        'ENCHANTRESS',
                        'JAKIRO',
                        'CHEN',
                        'SILENCER',
                        'RUBICK',
                        'DISRUPTOR',
                        'KEEPER OF THE LIGHT',
                        'SKYWRATH MAGE',
                        'ORACLE',
                        'TECHIES',
                        'DARK WILLOW',
                        'SHADOW FIEND',
                        'RAZOR',
                        'VENOMANCER',
                        'VIPER',
                        'CLINKZ',
                        'WEAVER',
                        'MEDUSA',
                        'ARC WARDEN',
                        'BANE',
                        'LICH',
                        'LION',
                        'WITCH DOCTOR',
                        'ENIGMA',
                        'NECROPHOS',
                        'WARLOCK',
                        'QUEEN OF PAIN',
                        'DEATH PROPHET',
                        'PUGNA',
                        'DAZZLE',
                        'LESHRAC',
                        'BATRIDER',
                        'ANCIENT APPARITION',
                        'INVOKER',
                        'OUTWORLD DEVOURER',
                        'SHADOW DEMON',
                        'VISAGE',
                        'WINTER WYVERN',
                        'GRIMSTROKE'],
             'Support': ['EARTHSHAKER',
                         'KUNKKA',
                         'OMNIKNIGHT',
                         'ALCHEMIST',
                         'TREANT PROTECTOR',
                         'IO',
                         'PHOENIX',
                         'SNAPFIRE',
                         'MIRANA',
                         'VENGEFUL SPIRIT',
                         'NAGA SIREN',
                         'CRYSTAL MAIDEN',
                         'WINDRANGER',
                         'LINA',
                         'SHADOW SHAMAN',
                         'ENCHANTRESS',
                         'JAKIRO',
                         'CHEN',
                         'SILENCER',
                         'OGRE MAGI',
                         'RUBICK',
                         'DISRUPTOR',
                         'KEEPER OF THE LIGHT',
                         'SKYWRATH MAGE',
                         'ORACLE',
                         'DARK WILLOW',
                         'SAND KING',
                         'WRAITH KING',
                         'UNDYING',
                         'ABADDON',
                         'UNDERLORD',
                         'VENOMANCER',
                         'BANE',
                         'LICH',
                         'LION',
                         'WITCH DOCTOR',
                         'WARLOCK',
                         'DAZZLE',
                         'LESHRAC',
                         'ANCIENT APPARITION',
                         'SHADOW DEMON',
                         'VISAGE',
                         'WINTER WYVERN',
                         'GRIMSTROKE']}